name: Delpoy to AWS (CDK)

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Allows changes to the repository contents (including workflows)
  workflows: write  # Allows workflow creation/modification

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
        
      - name: Install CDK dependencies
        working-directory: ./
        run: npm ci

      - name: Deploy CDK stack
        working-directory: ./
        run: npx cdk deploy --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.BETA_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BETA_AWS_SECRET_KEY }}
          AWS_REGION: "us-east-1"